extends: default

rules:
  document-start: disable
  new-line-at-end-of-file: disable
  line-length: disable
  braces: disable
# ignore: |

#   # folders
#   themes/

#   # files
#   secrets.example.yaml
