---
- name: "Setup computer and configure stuff"
  hosts: all
  gather_facts: true
  vars:
    # your extra bundles here
    # zsh_antigen_bundles_extras: []
    # your variables here
    # zsh_autosuggestions_bind_key: "^U"
  vars_files:
    - defaults/main.yml

  tasks:
    - name: Install stuff
      ansible.builtin.include_tasks: tasks/install.yml
      tags:
        - zsh
        - install

    - name: Configure zsh
      ansible.builtin.include_tasks: tasks/configure.yml
      tags:
        - zsh
        - configure

    - name: Post installation stuff
      ansible.builtin.include_tasks: tasks/post-install.yml
      tags:
        - zsh
        - install
        - post_install

    - name: Enabled for more users
      ansible.builtin.include_tasks: tasks/source-for-users-shared.yml
      tags:
        - zsh
        - install
      when: zsh_shared or zsh_source_for_all_users and not (ansible_os_family == 'Darwin')

    - name: Reset antigen cache
      ansible.builtin.command: "timeout 10s /bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
      become: true
      become_user: "{{ zsh_user }}"
      changed_when: false
      failed_when: false
      tags: always
