---
- name: Install stuff
  ansible.builtin.include_tasks: install.yml
  tags:
    - zsh
    - install

- name: Configure zsh
  ansible.builtin.include_tasks: configure.yml
  tags:
    - zsh
    - configure

- name: Post installation stuff
  ansible.builtin.include_tasks: post-install.yml
  tags:
    - zsh
    - install
    - post_install

- name: Enabled for more users
  ansible.builtin.include_tasks: source-for-users-shared.yml
  when: zsh_shared or zsh_source_for_all_users

- name: Reset antigen cache
  ansible.builtin.command: "timeout 10s /bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
  tags: always
