---
- include_tasks: install.yml
  name: Install stuff
  tags:
    - zsh
    - install

- include_tasks: configure.yml
  name: Configure zsh
  tags:
    - zsh
    - configure

- include_tasks: post-install.yml
  name: Post installation stuff
  tags:
    - zsh
    - install
    - post_install

- include_tasks: source-for-users-shared.yml
  tags:
    - zsh
    - install
  when: zsh_shared or zsh_source_for_all_users

- name: Reset antigen cache
  command: "timeout 10s /bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: true
  become_user: '{{ zsh_user }}'
  changed_when: false
  failed_when: false
  tags: always
