---
- name: Reset antigen cache
  ansible.builtin.command: "timeout 10s /bin/zsh -c 'source {{ zsh_config }}; antigen reset'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false

- name: Update antigen bundles
  ansible.builtin.command: "timeout 30s /bin/zsh -c 'source {{ zsh_config }}; antigen update'"
  become: true
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
