- name: Get users's home path
  ansible.builtin.shell: "egrep '^.*:.*:[1-9][0-9]{3,4}:.*:.*:.*:.*(bash|zsh)$' /etc/passwd | awk -F: '{print $6}'"
  register: paths
  changed_when: false

- name: Get users
  ansible.builtin.shell: "egrep '^.*:.*:[1-9][0-9]{3,4}:.*:.*:.*:.*(bash|zsh)$' /etc/passwd | awk -F: '{print $1}'"
  register: zsh_users
  when: paths is defined and paths.stdout != ""
  changed_when: false

- name: Format user list
  ansible.builtin.set_fact:
    zsh_list_users: "{{ ['root', 'root'] + zsh_users.stdout.splitlines() | list }}"
  when: paths is defined and paths.stdout != ""

- name: Merge the users path and root/skel to list
  ansible.builtin.set_fact:
    allpaths: "{{ ['/root', '/etc/skel'] + paths.stdout.splitlines() | list }}"
  when: paths is defined and paths.stdout != ""

- name: Write .zshrc config for all users
  ansible.builtin.template:
    src: zshrc.j2
    mode: 0755
    dest: "{{ zsh_config }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    backup: true
  loop: "{{ allpaths }}"
  when: not zsh_shared and zsh_change_user_shell and allpaths is defined

- name: Install .zshrc shared between users
  ansible.builtin.copy:
    content: source /usr/share/zsh-config/.zshrc
    dest: "{{ item }}/.zshrc"
    owner: "{{ zsh_list_users[id] | default('root') }}"
    mode: "0644"
  loop: "{{ allpaths }}"
  loop_control:
    index_var: id
  become: true
  when: zsh_shared and allpaths is defined
