---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "bruvv.zsh_antigen"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux9
          - rockylinux8
          - ubuntu2204
          - debian11
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: "bruvv.zsh_antigen"

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible docker 'molecule[docker]' ansible-lint yamllint flake8

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Injecting a dynamic Collection version
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          galaxy_version: "${{ env.RELEASE_VERSION }}"
      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          collection_dir: "meta"
