---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "bruvv.zsh_antigen"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux9
          - rockylinux8
          - ubuntu2204
          - debian11
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: "bruvv.zsh_antigen"

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible docker 'molecule[docker]' ansible-lint yamllint flake8

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
      - uses: phish108/autotag-action@1.1.53
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
